#ifndef MINI_FACTORY_ANIMATION_ID_H_
#define MINI_FACTORY_ANIMATION_ID_H_

typedef enum AnimationID {
	BELT_UP,
	BELT_DOWN,
	BELT_LEFT,
	BELT_RIGHT,
	BELT_UP_LEFT,
	BELT_UP_RIGHT,
	BELT_DOWN_LEFT,
	BELT_DOWN_RIGHT,
	BELT_LEFT_UP,
	BELT_LEFT_DOWN,
	BELT_RIGHT_UP,
	BELT_RIGHT_DOWN
} AnimationID;

#endif
